GET http://localhost:3000/api/1451001600000 HTTP/1.1

################################

GET http://localhost:3000/api/2015-12-28 HTTP/1.1

################################

GET http://localhost:3000/api/qwerfasdf HTTP/1.1

################################

GET http://localhost:3000/api/1551001600000? HTTP/1.1

################################

GET http://localhost:3000/api/1995-12-17TKK13:24:00 HTTP/1.1

################################

GET http://localhost:3000/api/asdfasdf HTTP/1.1

################################

GET http://localhost:3000/api/ HTTP/1.1

################################
